# http://www.mac52ipod.cn/post/watch-youku-tudou-iqiyi-sohu-letv-movie-on-ios-ipad-iphone-in-foreign-country.php
blacklist:
  # google
  - google.com
  - google.com.hk
  - google.
  - gstatic.com
  - googleapis.com
  - googlecode.com
  - appspot.com
  - googleusercontent.com
  - googlesyndication.com
  - googletagservices.com
  - google-analytics.com
  - doubleclick.net
  - feedburner.com

  - blogspot.com
  - blogspot.jp
  - blogger.com

  # youbute
  - youtube.com
  - ytimg.com
  - googlevideo.com

  # vimeo
  - vimeo.com
  - vimeocdn.com

  # dropbox
  # - http://*.dropbox.com* # http://notify7.dropbox.com
  - dropbox.com

  # facebook
  - facebook.com
  - fbcdn-*.akamaihd.net
  - fbstatic-*.akamaihd.net
  - fbexternal-*.akamaihd.net

  # twitter
  - twitter.com
  - twimg.com
  - tweetmarker.net
  - t.co

  - mobile01.com
  - slideshare.net
  - cdn.wallwiz.com
  - bbc.co.uk
  - xsellize.com
  - wordpress.com
  - gitlab.com
  - pastie.org

  # slowly
  - staticinstapaper.s3.amazonaws.com
  - libsyn.com

whitelist:
  # sunteya's list
  - lvh.me
  - wido.me
  - 25pp.com
  - tongbu.com
  - leaderhero.com
  - guoku.com
  - .lan
  - .dev
  - .local
  - leiphone.com
  - zhihu.com
  - ifanr.com
  - jiaren.org
  - iapps.im
  - chiphell.com
  - dgtle.com
  - mzstatic.com
  - phobos.apple.com
  - tencent.com
  - 36krcnd.com
  - fengbuy.com
  - hiwifi.com
  - vmall.com
  - yixun.com
  - images-amazon.com
  - shipin8.com

  - chdbits.org
  - hdwing.com
  - open.cd
  - m-team.cc
  - miwifi.com
  - bigbata.com

  # skip top Chinese sites
  # source: 
  # (1) custom list
  # (2) https://dl-web.dropbox.com/u/3241202/apps/chn-cdn/dnsmasq.server.conf
  # (3) Domestic CDN and cloud
  # (4) alexa 500
  #     less all the cn domains
  #     less google.com.hk, google.com, google.co.uk, googleusercontent.com
  #     google.com.tw, tumblr.com, wikipedia.org, youtube, github, wordpress
  #     wsj.com, godaddy,stackoverflow.com, zaobao.com
  #  # custom list. feel free to add.
  # mostly ad servers and img servers
  - kandian.com
  - homeinns.com
  - sinajs.com
  - douban.fm
  - pixlr.com
  - jing.fm
  - oadz.com
  - youshang.com
  - kuaidi100.com
  - sinahk.net
  - kuaidi100.com
  - adsame.com
  - scorecardresearch.com
  - imrworldwide.com
  - wrating.com
  - mediav.com
  - lycos.com
  - gamesville.com
  - lygo.com
  - quantserve.com
  - miaozhen.com
  - qstatic.com
  - tremormedia.com
  - yieldmanager.com
  - adsonar.com
  - adtechus.com
  - bluekai.com
  - ipinyou.com
  - bdstatic.com
  - bdimg.com
  - mediaplex.com
  - ykimg.com
  - irs01.com
  - irs01.net
  - mmstat.com
  - tanx.com
  - atdmt.com
  - tudouui.com
  - tdimg.com
  - ku6img.com
  - ku6cdn.com
  - staticsdo.com
  - snyu.com
  - mlt01.com
  - doubleclick.net
  - scanscout.com
  - betrad.com
  - invitemedia.com
  - adroll.com
  - mathtag.com
  - 2mdn.net
  - rtbidder.net
  - compete.com
  - vizu.com
  - adnxs.com
  - mookie1.com
  - pubmatic.com
  - serving-sys.com
  - legolas-media.com
  - harrenmedianetwork.com
  # - ytimg.com too slow
  - google-analytics.com

  # Chinese cloud
  - alipayobjects.com
  - aliyun.com
  - alicdn.com

  # ihipop's list
  - renren.com
  - sina.com
  - iask.com
  - cctv*.com
  - img.cctvpic.com
  - 163.com
  - netease.com
  - 126.net
  - qq.com
  - ptlogin2.qq.com
  - gtimg.com
  - taobao.com
  - taobaocdn.com
  - lxdns.com
  - sohu.com
  - ifeng.com
  - jysq.net
  - nipic.com
  - fastcdn.com
  - oeeee.com
  - mosso.com
  - pengyou.com
  - 360buyimg.com
  - 51buy.com
  - paipaiimg.com
  - icson.com

  # alexa top 500 chinese sites
  - baidu.com
  - qq.com
  - taobao.com
  - 163.com
  - weibo.com
  - sohu.com
  - youku.com
  - soso.com
  - ifeng.com
  - tmall.com
  - hao123.com
  - tudou.com
  - jd.com
  - 360buy.com
  - chinaz.com
  - alipay.com
  - sogou.com
  - renren.com
  - cnzz.com
  - douban.com
  - pengyou.com
  - yahoo.com
  - 58.com
  - alibaba.com
  - 56.com
  - xunlei.com
  - bing.com
  - iqiyi.com
  - csdn.net
  - soku.com
  - xinhuanet.com
  - ku6.com
  - aizhan.com
  - 4399.com
  - yesky.com
  - soufun.com
  - youdao.com
  - china.com
  - hudong.com
  - ganji.com
  - kaixin001.com
  - paipai.com
  - live.com
  - alimama.com
  - mop.com
  - 51.la
  - 51job.com
  - dianping.com
  - 126.com
  - admin5.com
  - it168.com
  - 2345.com
  - huanqiu.com
  - arpg2.com
  - 777wyx.com
  - chinanews.com
  - letv.com
  - jiayuan.com
  - 39.net
  - twcczhu.com
  - cnblogs.com
  - microsoft.com
  - dangdang.com
  - pchome.net
  - pptv.com
  - vancl.com
  - zhaopin.com
  - apple.com
  - bitauto.com
  - etao.com
  - qunar.com
  - eastmoney.com
  - yihaodian.com
  - 115.com
  - 21cn.com
  - blog.163.com
  - hupu.com
  - duowan.com
  - 52pk.net
  - baixing.com
  - iteye.com
  - verycd.com
  - suning.com
  - discuz.net
  - 7k7k.com
  - mtime.com
  - msn.com
  - ccb.com
  - hc360.com
  - cmbchina.com
  - 51.com
  - yoka.com
  - seowhy.com
  - chinabyte.com
  - qidian.com
  - ctrip.com
  - cnbeta.com
  - tom.com
  - tenpay.com
  - meituan.com
  - 120ask.com
  - yahoo.co.jp
  - ebay.com
  - 51cto.com
  - sdo.com
  - meilishuo.com
  - 17173.com
  - xyxy.net
  - 19lou.com
  - yiqifa.com
  - nuomi.com
  - eastday.com
  - onlinedown.net
  - oschina.net
  - zhubajie.com
  - amazon.com
  - babytree.com
  - kdnet.net
  - docin.com
  - qq937.com
  - tgbus.com
  - 51buy.com
  - nipic.com
  - im286.com
  - baomihua.com
  - doubleclick.com
  - dh818.com
  - ads8.com
  - hiapk.com
  - ynet.com
  - sootoo.com
  - mogujie.com
  - gfan.com
  - ppstream.com
  - a135.net
  - ip138.com
  - zx915.com
  - lashou.com
  - crsky.com
  - iciba.com
  - uuzu.com
  - tuan800.com
  - haodf.com
  - youboy.com
  - ulink.cc
  - qiyou.com
  - 88db.com
  - tao123.com
  - 178.com
  - ci123.com
  - yolk7.com
  - tiexue.net
  - stockstar.com
  - xici.net
  - pcpop.com
  - linkedin.com
  - weiphone.com
  - feng.com
  - doc88.com
  - adobe.com
  - shangdu.com
  - aili.com
  - anjuke.com
  - 360doc.com
  - cnxad.com
  - west263.com
  - jiathis.com
  - gougou.com
  - whlongda.com
  - mnwan.com
  - onetad.com
  - duote.com
  - 55bbs.com
  - iloveyouxi.com
  - gongchang.com
  - meishichina.com
  - qire123.com
  - 55tuan.com
  - cocoren.com
  - xiaomi.com
  - phpwind.net
  - abchina.com
  - thethirdmedia.com
  - coo8.com
  - aliexpress.com
  - onlylady.com
  - manzuo.com
  - elong.com
  - aibang.com
  - 10010.com
  - 3366.com
  - 28tui.com
  - vipshop.com
  - 1616.net
  - pp.cc
  - jumei.com
  - tui18.com
  - 52tlbb.com
  - yinyuetai.com
  - eye.rs
  - baihe.com
  - iyaya.com
  - imanhua.com
  - lusongsong.com
  - taobaocdn.com
  - leho.com
  - 315che.com
  - donews.com
  - cqnews.net
  - 591hx.com
  - 114la.com
  - gamersky.com
  - tangdou.com
  - 91.com
  - uuu9.com
  - xinnet.com
  - dedecms.com
  - cnmo.com
  - 51fanli.com
  - liebiao.com
  - yyets.com
  - lady8844.com
  - newsmth.net
  - ucjoy.com
  - duba.net
  - cnki.net
  - 70e.com
  - funshion.com
  - qjy168.com
  - paypal.com
  - 3dmgame.com
  - m18.com
  - caixin.com
  - linezing.com
  - 53kf.com
  - makepolo.com
  - dospy.com
  - xiami.com
  - 5173.com
  - vjia.com
  - hotsales.net
  - 4738.com
  - mydrivers.com
  - alisoft.com
  - titan24.com
  - u17.com
  - jb51.net
  - diandian.com
  - dzwww.com
  - hichina.com
  - abang.com
  - qianlong.com
  - m1905.com
  - chinahr.com
  - zhaodao123.com
  - daqi.com
  - sourceforge.net
  - yaolan.com
  - 5d6d.net
  - fobshanghai.com
  - q150.com
  - l99.com
  - ccidnet.com
  - aifang.com
  - aol.com
  - theplanet.com
  - chinaunix.net
  - hf365.com
  - ad1111.com
  - zhihu.com
  - blueidea.com
  - net114.com
  - 07073.com
  - alivv.com
  - mplife.com
  - allyes.com
  - jqw.com
  - netease.com
  - 1ting.com
  - yougou.com
  - dbank.com
  - made-in-china.com
  - 36kr.com
  - wumii.com
  - zoosnet.net
  - xitek.com
  - ali213.net
  - exam8.com
  - jxedt.com
  - uniontoufang.com
  - zqgame.com
  - 52kmh.com
  - yxlady.com
  - sznews.com
  - longhoo.net
  - game3737.com
  - 51auto.com
  - booksky.org
  - iqilu.com
  - ddmap.com
  - cncn.com
  - ename.net
  - 1778.com
  - blogchina.com
  - 778669.com
  - dayoo.com
  - ct10000.com
  - zhibo8.cc
  - qingdaonews.com
  - zongheng.com
  - 1o26.com
  - oeeee.com
  - tiancity.com
  - jinti.com
  - si.kz
  - tuniu.com
  - xiu.com
  - 265.com
  - gamestlbb.com
  - 2hua.com
  - moonbasa.com
  - sf-express.com
  - qiushibaike.com
  - ztgame.com
  - yupoo.com
  - kimiss.com
  - cnhubei.com
  - pingan.com
  - lafaso.com
  - rakuten.co.jp
  - zhenai.com
  - tiao8.info
  - 7c.com
  - tianji.com
  - kugou.com
  - house365.com
  - flickr.com
  - xiazaiba.com
  - aipai.com
  - sodu.org
  - bankcomm.com
  - lietou.com
  - toocle.com
  - fengniao.com
  - 99bill.com
  - bendibao.com
  - mapbar.com
  - nowec.com
  - yingjiesheng.com
  - comsenz.com
  - meilele.com
  - otwan.com
  - 61.com
  - meizu.com
  - readnovel.com
  - fenzhi.com
  - up2c.com
  - 500wan.com
  - fx120.net
  - ftuan.com
  - 17u.com
  - lehecai.com
  - 28.com
  - bilibili.tv
  - huaban.com
  - szhome.com
  - miercn.com
  - fblife.com
  - chinaw3.com
  - smzdm.com
  - b2b168.com
  - 265g.com
  - anzhi.com
  - chuangelm.com
  - php100.com
  - 100ye.com
  - hefei.cc
  - mumayi.com
  - sttlbb.com
  - mangocity.com
  - fantong.com